import React, { useState } from 'react'
import Head from "next/head";
import Image from 'next/image'
import { useRouter } from 'next/router';

export default function index() {
  const route = useRouter();
  const [user, setUser] = useState('Anonymous')


  const showElement = (id) => {
    const element = document.getElementById(id)
    if (element.classList.contains('show')) {
      element.classList.remove('show');
    } else {
      element.classList.add('show');
    }
  }

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      {/* <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">

            <span className='row text-center justify-content-between align-content-center'>
              <Image src={'/bg.jpg'} width={50} height={50} className='col' alt='logo' />
              <div className='col h-100 text-center '>MyWebsite</div>
            </span>
          </a>

          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav ms-auto">
              <li className="nav-item">
                <a className="nav-link active" aria-current="page" href="#">
                  Home
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">
                  Features
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">
                  Pricing
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">
                  Contact
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav> */}


      <nav className="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div className="navbar-brand" >
          <button className='mr-1 btn '
            onClick={() => route.push('/authen')}
          >


            <Image src={'/churchs.jpeg'} width={55} height={50} alt='Home icon' className='rounded-circle m-lg-0' />
            <span className='text-white' style={{ marginRight: 10 }}>Logo home</span>
          </button>
        </div>
        <button className="navbar-toggler" type="button"
          onClick={() => showElement('navbarCollapse')}
        >
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="navbar-collapse collapse " id="navbarCollapse" >
          <ul className="navbar-nav ms-auto me-auto">
            <li className="nav-item active">
              <a className="nav-link" href="#">Home</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#">Link</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#">Disabled</a>
            </li>
          </ul>
          <div className="mr-auto justify-content-between" style={{ paddingRight: 10 }}>
            {/* <button className='mr-1 btn '
              onClick={() => route.push('/authen')}
            >
              <text className='text-white' style={{ marginRight: 10, fontSize: 18, fontFamily: 'cursive' }}>{user !== '' ? `${user}` : ''}</text>

              <Image src={'/user.png'} width={40} height={40} alt='user icon' />
            </button> */}


            <div className="dropdown">
              <text className='text-white' style={{ fontSize: 18, fontFamily: 'cursive' }}>{user !== '' ? `${user}` : ''}</text>
              <button
                className="btn bg-dark dropdown-toggle"
                style={{ color: 'white' }}
                type="button"
                id="userDropdown"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                onClick={() =>
                  showElement('userLogin')}
              >
              </button>

              <ul className="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown" id="userLogin">

                <li>
                  Logout
                </li>
                <li>
                  Login
                </li>

              </ul>
            </div>
          </div>
        </div>

      </nav>


      {/* Main Layout */}
      <div className="container-fluid mt-5 vh-100">
        <div className="row">
          {/* Left Advertisement Section */}
          <div className="col-md-2 col-2 d-none d-md-block position-fixed mt-5" style={{ marginTop: '10%', top: '0', left: '0', height: '100vh', width: '16.6%' }}>
            <div className="p-3 bg-light border rounded h-100">
              <h5 className="text-center">Advertisement</h5>
              <p>Left Ad Content Here</p>
            </div>
          </div>

          {/* Main Content Section */}
          <div className="col-12 col-md-8 offset-md-2 mt-3">
            <div className="p-4 bg-white border rounded shadow-sm ">
              <h2>Main Content Area</h2>
              <p>
                This is the main content area. You can put articles, images,
                videos, or anything else here.
              </p>
              <p>
                Bootstrap helps in making the layout responsive. The left and
                right advertisements are only visible on medium to large
                screens.
              </p>
            </div>
          </div>

          {/* Right Advertisement Section */}
          <div className="col-md-2  col-2 d-none d-md-block position-fixed mt-5" style={{ top: '0', right: '0', height: '100vh', width: '16.6%' }}>
            <div className="p-3 bg-light border rounded h-100">
              <h5 className="text-center">Advertisement</h5>
              <p>Right Ad Content Here</p>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
