import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["vietnamese"] });

export default function Home() {

  const [rememberMe, setRememberMe] = useState('login');

  return (
    < >
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-IwUSj6Zsksl/SypHlG7rJ9LBtO4VfuRlPhQ+FdPRHdpn72ABXHzhvJ7AxVYWvNTZ3tQ2WZw18zLsHdc1XWmELg=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />

      </Head>


      <div className="container-fluid login_background_image" >
        <div className="row justify-content-center align-items-center">
          <div className="col-lg-4  mt-5">
            <div className="row justify-content-center text-center mb-4">
              <h3 className="btn-loggin" >Login</h3>
            </div>
            <form action={"/login"}>
              <div className="form-group mb-3">
                <input
                  type="email"
                  className="form-control form-control-placeholder opacity-75"
                  id="loginEmail"
                  placeholder="Enter your email"
                  required
                />
              </div>
              <div className="form-group mb-3">
                <input
                  type="password"
                  className="form-control form-control-placeholder opacity-75"
                  id="loginPassword"
                  placeholder="Password"
                  required
                />
              </div>
              <button type="submit" className="form-control btn_loggin ">
                Login
              </button>
            </form>
            <div className="row mt-2 text-center">
              <div className="w-50">
                <label style={{ color: 'white' }}>
                  <input type="checkbox" id="chk_remember" style={{ marginRight: '8px' }} onChange={(event) => { console.log(event.target.checked) }} />
                  Remember Me
                </label>
              </div>
              <div className="w-50">

                <a href="#" className="text-light text-decoration-none hover">Forgot Password?</a>

              </div>
              <div className="w-100 text-center m-2">
                <label style={{ color: 'lightyellow' }}>--Or--</label>
                <div>
                  <i class="fa-brands fa-facebook" aria-hidden="true"></i>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>



    </>
  );
}
